### PR TITLE
Added ability to search Google Maps

### PR DESCRIPTION
**Pull request by module17**
Quickly query Google Maps from the command line with -m or --maps option.

### CODE REVIEW

**Comment by mrowa44** [comment]
No offence, but how often do you need to use Google Maps while on cli?

**Comment by module17** [comment]
Just as often as querying Google Images or Youtube.

**Comment by mrowa44** [comment]
Well maybe, but Google Maps feels like a little overkill for such a simple gem

**Comment by module17** [comment]
Best of luck with it!

**Pull request closed without merging**
